general:
steps:
 gctsDeploy:
  host: "https://vhcals4hci:44300"
  client: "200"
  abapCredentialsId: "VILLALOBOSE"
  repository: "ervigue-gcts_abap_demos"
  remoteRepositoryURL: "https://github.com/ErVigue/gCTS_ABAP_DEMOS"
  role: "SOURCE"
  vSID: "QWE"
  Type: "GIT"
  verbose: true

